language: r
sudo: false
cache: packages

r_github_packages:
  - IRkernel/repr
  - IRkernel/IRdisplay

addons:
  apt:
    packages:
      - python3
      - python3-setuptools

script:
  - source .travis-build.sh
