language: python
sudo: false
python:
  - "3.5"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment -c r r r-uuid r-digest r-base64enc
            r-evaluate r-jsonlite jupyter pip zeromq=4.0* r-rzmq
  - source activate test-environment
  - pip install jupyter_kernel_test
  - R -e "install.packages(c('repr','IRdisplay'),
            repos = 'http://irkernel.github.io/')"
  - R CMD INSTALL $TRAVIS_BUILD_DIR
  - R -e "IRkernel::installspec()"

script:
  - python test_ir.py
